### ISSUE TITLE
Color is not parsing correctly

### ISSUE THREAD

**Issue by stephvatz** [tilemill-project/tilemill#1724]
I have my CSS in Styles written like so:

``` css

Map {
  background-color: #b8dee6;
}

#countries {
  ::outline {
    line-color: #85c5d3;
    line-width: 2;
    line-join: round;
  }
  polygon-fill: #eee;
}
#unemployment {
  line-color:#565A5D;
  line-width:0.5;
  polygon-opacity:1;
  polygon-fill:#ae8;
}

#unemployment[RATE<=0.30] {
   polygon-fill:#660719
}
#unemployment[RATE<=0.20] {
   polygon-fill:#850920
}
#unemployment[RATE<=0.18] {
   polygon-fill:#940b24
}
#unemployment[RATE<=0.17] {
   polygon-fill:#a40c27
}
```

Although no error message is popping up and my ID is correct, I don't know why it isn't recognizing the CSS..?
