### ISSUE TITLE
Use of HTML entities in text-name property causes "XML malformed" error

### ISSUE THREAD

**Issue by IvanSanchez** [tilemill-project/tilemill#901]
How to reproduce: get your favourite style and (inadvertely) put a HTML entity on a text-name property.

For example, this:

``` css
#route[type='plane']
{
  text-name: "'Avión'";
}
```

will work fine, but this:

``` css
#route[type='plane']
{
  text-name: "'Avi&oacute;n'";
}
```

returns a "Error: XML document not well formed: " error. In an ideal world, HTML entities should be no reason for crashing.
