### ISSUE TITLE
Blank tiles if using nonexistent filter selector

### ISSUE THREAD

**Issue by IvanSanchez** [tilemill-project/tilemill#950]
OK, the title of this bug is a bit confusing. Better to explain with the way to reproduce it.

Put something like this in your .mss file:

``` css
#roads[highway='motorway']
{
   line-color:#808080;
   line-width:3;
}
```

That should work nicely. Now, include a typo in the filter selector, like this:

``` css
#roads[hihhggghway='motorway']
{
   line-color:#808080;
   line-width:3;
}
```

Something, somewhere, will silently crash, with no visible black popup, no error highlighting in the .mss editor, and no clues whatsoever in the tilemill.log.

The desired behaviour would be to highlight the line in the .mss file containing the invalid filter selector.
